name: minimalist
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  android_intent_plus: ^5.1.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "lib/assets/icon.png"
  adaptive_icon_foreground: "lib/assets/icon_foreground.png"
  adaptive_icon_background: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - lib/assets/
